apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: inventorymanagementingress
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: inventorymanagementsvc
          servicePort: 80
  - host: bar.foo.com
    http:
      paths:
      - backend:
          serviceName: inventorymanagementsvc
          servicePort: 8011